/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;

import javax.swing.JOptionPane;

/**
 *
 * @author Edvania
 */
public class AppMatrizDeInteiros extends javax.swing.JFrame {

    /**
     * Creates new form AppMatrizDeInteiros
     */
    public AppMatrizDeInteiros() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOrdemMatriz = new javax.swing.JPanel();
        lblOrdemMatr = new javax.swing.JLabel();
        lblLinhas = new javax.swing.JLabel();
        lblColunas = new javax.swing.JLabel();
        txtLinhas = new javax.swing.JTextField();
        txtColunas = new javax.swing.JTextField();
        splMatriz = new javax.swing.JScrollPane();
        tblMatriz = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnlOperacoes = new javax.swing.JPanel();
        lblOperacoes = new javax.swing.JLabel();
        btnDefinirMartiz = new javax.swing.JButton();
        btnGerarMatriz = new javax.swing.JButton();
        btnDiagPrincipa = new javax.swing.JButton();
        btnDiagSecundaria = new javax.swing.JButton();
        btnSomaLinhas = new javax.swing.JButton();
        btnSomaColunas = new javax.swing.JButton();
        btnTransposta = new javax.swing.JButton();
        btnBuscaValor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlOrdemMatriz.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlOrdemMatriz.setName("pnlOrdemMatriz"); // NOI18N

        lblOrdemMatr.setText("Ordem da Matriz: ");

        lblLinhas.setText("Linhas: ");

        lblColunas.setText("Colunas:");

        javax.swing.GroupLayout pnlOrdemMatrizLayout = new javax.swing.GroupLayout(pnlOrdemMatriz);
        pnlOrdemMatriz.setLayout(pnlOrdemMatrizLayout);
        pnlOrdemMatrizLayout.setHorizontalGroup(
            pnlOrdemMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdemMatrizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrdemMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrdemMatr)
                    .addGroup(pnlOrdemMatrizLayout.createSequentialGroup()
                        .addComponent(lblLinhas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(lblColunas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtColunas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pnlOrdemMatrizLayout.setVerticalGroup(
            pnlOrdemMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdemMatrizLayout.createSequentialGroup()
                .addComponent(lblOrdemMatr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrdemMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinhas)
                    .addComponent(lblColunas)
                    .addComponent(txtLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        splMatriz.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        splMatriz.setViewportView(tblMatriz);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        pnlOperacoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblOperacoes.setText("Operaçoes");

        btnDefinirMartiz.setText("Definir Matriz");
        btnDefinirMartiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefinirMartizActionPerformed(evt);
            }
        });

        btnGerarMatriz.setText("Gerar Matriz");

        btnDiagPrincipa.setText("Diag Principal");

        btnDiagSecundaria.setText("Diag Secundaria");

        btnSomaLinhas.setText("Soma Linhas");

        btnSomaColunas.setText("Soma Colunas");

        btnTransposta.setText("Transposta");

        btnBuscaValor.setText("Busca Valor");
        btnBuscaValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOperacoesLayout = new javax.swing.GroupLayout(pnlOperacoes);
        pnlOperacoes.setLayout(pnlOperacoesLayout);
        pnlOperacoesLayout.setHorizontalGroup(
            pnlOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperacoesLayout.createSequentialGroup()
                .addGroup(pnlOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOperacoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblOperacoes))
                    .addGroup(pnlOperacoesLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(pnlOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGerarMatriz)
                            .addComponent(btnDefinirMartiz)
                            .addComponent(btnDiagPrincipa)
                            .addComponent(btnDiagSecundaria)
                            .addComponent(btnSomaLinhas)
                            .addComponent(btnSomaColunas)
                            .addComponent(btnTransposta)
                            .addComponent(btnBuscaValor))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlOperacoesLayout.setVerticalGroup(
            pnlOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOperacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDefinirMartiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerarMatriz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDiagPrincipa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDiagSecundaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSomaLinhas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSomaColunas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransposta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscaValor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(splMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlOrdemMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(pnlOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlOrdemMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(splMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Boolean validaLinhas() {
        if (txtLinhas.getText().isEmpty() || 
            Integer.parseInt(txtLinhas.getText()) <= 0) {
            JOptionPane.showMessageDialog(
                    this, 
                    "Informe um valor valido para linhas", 
                    "Manipula Matriz",
                    0);
            return true;
        } else {
            return false;
        }
    }
    
    private Boolean validaColunas() {
        if (txtColunas.getText().isEmpty() || 
            Integer.parseInt(txtColunas.getText()) <= 0) {
            JOptionPane.showMessageDialog(
                    this, 
                    "Informe um valor valido para Colunas", 
                    "Manipula Matriz", 
                    0);
            return true;
        } else {
            return false;
        }
    }
    
    private void btnBuscaValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscaValorActionPerformed

    private void btnDefinirMartizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefinirMartizActionPerformed
       if (validaLinhas() || validaColunas()) {
           
       }
    }//GEN-LAST:event_btnDefinirMartizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMatrizDeInteiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMatrizDeInteiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMatrizDeInteiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMatrizDeInteiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMatrizDeInteiros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaValor;
    private javax.swing.JButton btnDefinirMartiz;
    private javax.swing.JButton btnDiagPrincipa;
    private javax.swing.JButton btnDiagSecundaria;
    private javax.swing.JButton btnGerarMatriz;
    private javax.swing.JButton btnSomaColunas;
    private javax.swing.JButton btnSomaLinhas;
    private javax.swing.JButton btnTransposta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblColunas;
    private javax.swing.JLabel lblLinhas;
    private javax.swing.JLabel lblOperacoes;
    private javax.swing.JLabel lblOrdemMatr;
    private javax.swing.JPanel pnlOperacoes;
    private javax.swing.JPanel pnlOrdemMatriz;
    private javax.swing.JScrollPane splMatriz;
    private javax.swing.JTable tblMatriz;
    private javax.swing.JTextField txtColunas;
    private javax.swing.JTextField txtLinhas;
    // End of variables declaration//GEN-END:variables
}
